name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions: write-all

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: AI Code Review
        uses: intuit/auto-code-review@v1.0.4
        with:
          openai-key: ${{ secrets.OPENAI_API_KEY }}
          language: python
          files-changed: "sample.py"
