name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo (your project)
        uses: actions/checkout@v3

      - name: Checkout AI Reviewer code
        uses: actions/checkout@v3
        with:
          repository: Rimi04source/ai-reviewer
          path: ai-reviewer

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run AI Review script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python ai-reviewer/ai/github_reviewer.py
